# **IMPORT MODULES**

In [52]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# **DATASET LOADING**

In [53]:
df = pd.read_csv('/content/heart_disease.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [54]:
df.tail()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [55]:
df.shape

(918, 12)

In [56]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [57]:
df.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [58]:
df['HeartDisease'].value_counts()

HeartDisease
1    508
0    410
Name: count, dtype: int64

# **DATA PREPROCESSING**

In [59]:
# X -> Inputs and y -> Target values
X = df.drop('HeartDisease', axis = 1) # Drop Target column
y = df['HeartDisease'] # Contains only Target column

# Identify categorical columns and apply one-hot encoding
categorical_cols = X.select_dtypes(include='object').columns
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True) # drop_first=True to avoid multicollinearity

# Use train_test_split to split train and test dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Standard Scaler to scale features
scaler = StandardScaler()

# Apply StandardScaler on Inputs
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled)
print(X_test_scaled)

[[-1.24506731 -0.70898547  0.372803   ... -0.83846064 -1.03325003
  -0.84792072]
 [-1.8862362  -0.16628515  0.08614581 ... -0.83846064 -1.03325003
   1.17935554]
 [ 0.25099346  0.91911549  0.12313384 ...  1.19266183  0.96781995
  -0.84792072]
 ...
 [ 0.67843939 -0.16628515  0.49301407 ...  1.19266183 -1.03325003
   1.17935554]
 [ 0.67843939  1.02765555 -1.84647842 ...  1.19266183 -1.03325003
   1.17935554]
 [-1.45879027  0.91911549  1.77834789 ... -0.83846064  0.96781995
  -0.84792072]]
[[ 0.99902384  0.37641517 -0.04331227 ... -0.83846064 -1.03325003
   1.17935554]
 [-0.06959099  0.64776533  2.94347064 ... -0.83846064  0.96781995
  -0.84792072]
 [ 1.2127468   1.46181581 -1.84647842 ... -0.83846064  0.96781995
  -0.84792072]
 ...
 [ 1.10588532  0.4306852   0.40979102 ...  1.19266183  0.96781995
  -0.84792072]
 [-0.49703693 -0.16628515  0.61322515 ... -0.83846064 -1.03325003
   1.17935554]
 [ 1.10588532  0.5934953  -1.84647842 ...  1.19266183  0.96781995
  -0.84792072]]

# **BUILD THE MODEL**

In [60]:
model = LogisticRegression(max_iter=1000)
# Fit the model with Inputs
model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

# **MAKE PREDICTIONS AND MEASURE VALIDATION METRICS**

In [62]:
y_pred = model.predict(X_test)

# Measure Accuracy:
accuracy = accuracy_score(y_test, y_pred)

# Classification Report:
classification_rep = classification_report(y_test, y_pred)

# Confusion Matrix:
confusion_mat = confusion_matrix(y_test, y_pred)

# Print
print(f"Accuracy of the Model: {accuracy}")
print(f"Classification report:\n{classification_rep}")
print(f"Confusion Matrix:\n{confusion_mat}")

Accuracy of the Model: 0.8532608695652174
Classification report:
              precision    recall  f1-score   support

           0       0.80      0.87      0.83        77
           1       0.90      0.84      0.87       107

    accuracy                           0.85       184
   macro avg       0.85      0.86      0.85       184
weighted avg       0.86      0.85      0.85       184

Confusion Matrix:
[[67 10]
 [17 90]]