#Importing Libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

#Data Collection And Analysis

In [ ]:
#loading diabetes dataset to Pandas DataFrame
diabetes_df = pd.read_csv('/content/diabetes.csv')

In [ ]:
diabetes_df.head()

   Pregnancies  Glucose  BloodPressure  SkinThickness  ...   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35  ...  33.6                     0.627   50        1
1            1       85             66             29  ...  26.6                     0.351   31        0
2            8      183             64              0  ...  23.3                     0.672   32        1
3            1       89             66             23  ...  28.1                     0.167   21        0
4            0      137             40             35  ...  43.1                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
diabetes_df.shape

(768, 9)

In [ ]:
diabetes_df.describe()

       Pregnancies     Glucose  BloodPressure  ...  DiabetesPedigreeFunction         Age     Outcome
count   768.000000  768.000000     768.000000  ...                768.000000  768.000000  768.000000
mean      3.845052  120.894531      69.105469  ...                  0.471876   33.240885    0.348958
std       3.369578   31.972618      19.355807  ...                  0.331329   11.760232    0.476951
min       0.000000    0.000000       0.000000  ...                  0.078000   21.000000    0.000000
25%       1.000000   99.000000      62.000000  ...                  0.243750   24.000000    0.000000
50%       3.000000  117.000000      72.000000  ...                  0.372500   29.000000    0.000000
75%       6.000000  140.250000      80.000000  ...                  0.626250   41.000000    1.000000
max      17.000000  199.000000     122.000000  ...                  2.420000   81.000000    1.000000

[8 rows x 9 columns]

In [ ]:
diabetes_df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
#separating data & labels
X=diabetes_df.drop(columns= 'Outcome', axis=1)
Y=diabetes_df['Outcome']

In [ ]:
print(X)
print(Y)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

#Data Standardization

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(X)

StandardScaler()

In [ ]:
std_data = scaler.transform(X)

In [ ]:
print(std_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [ ]:
X = std_data
Y = diabetes_df['Outcome']

#Training and Testing Data

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=1)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(768, 8) (614, 8) (154, 8)

In [ ]:
print(X_train)
print(Y_train)

[[-2.50952128e-01  3.30087080e-03 -8.84314245e-01 ...  5.08618960e-01
  -1.04156736e+00 -7.01198424e-01]
 [ 1.23388019e+00  1.72464386e+00  1.08020025e+00 ...  2.16704696e-01
  -1.47270110e-02  2.10669743e+00]
 [-8.44885053e-01 -2.78373437e-01  5.63222752e-01 ...  3.56315866e-01
  -7.69756680e-01 -7.86286177e-01]
 ...
 [-5.47918591e-01  1.12999810e+00  2.53036252e-01 ...  9.40144394e-01
  -1.02042653e+00 -2.75759658e-01]
 [-1.14185152e+00  2.22380888e-01 -5.71502470e-02 ... -1.89436889e-01
   2.77586265e+00 -7.01198424e-01]
 [-8.44885053e-01  1.84983245e+00 -3.57259724e+00 ...  1.43512945e+00
  -5.73448966e-01  6.60205626e-01]]
678    1
53     1
665    0
219    1
720    0
      ..
88     1
137    0
645    0
308    1
332    1
Name: Outcome, Length: 614, dtype: int64

#Training the Model

In [ ]:
classifier = svm.SVC(kernel='linear')

In [ ]:
#training data into classifier
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

#Model Evaluation

In [ ]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [ ]:
print(' accuracy score of training data: ',training_data_accuracy)

 accuracy score of training data:  0.7833876221498371

In [ ]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)
print(' accuracy score of test data: ',test_data_accuracy)

 accuracy score of test data:  0.7792207792207793

#Prediction

In [ ]:
input_data = (1,189,60,23,846,30.1,0.398,59)

#changing input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

#reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

#standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if(prediction[0]==0):
  print('The Person is Non-Diabetic')
else:
  print('The Person is Diabetic')

[[-0.84488505  2.13150675 -0.47073225  0.15453319  6.65283938 -0.24020459
  -0.2231152   2.19178518]]
[1]
The Person is Diabetic

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(